### ISSUE TITLE
Change submission form content

### ISSUE THREAD

**Issue by TmsLsk** [COVID-science-engine/crowdsourced-papers-prototype#10]
Submission form content needs to be slightly altered in line with: https://forms.gle/wJX9PW5AuGqynnzq6

**Comment by MatMoore** [comment]
👍 I'll do this next

**Comment by MatMoore** [comment]
@TmsLsk @SIMC4774 I've made some updates to the form here: https://covid-science-engine-prototype.herokuapp.com/submit

I think the design will need some further tweaking, as I copied the layout from helpwithcovid in order to get something working quickly. But this should capture the same fields as the google form.
